# Generated by Django 3.1.7 on 2021-03-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_auto_20210310_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/fotosapp/'),
        ),
    ]
